language: generic

services:
  - docker

script:
  - make docker

branches:
  only:
  - master
  
deploy:
  provider: releases
  # https://github.com/settings/tokens
  # Add variable TOKEN in TravisCI settings
  api_key: $GITHUB_TOKEN
  file:
    - "build/diploma.pdf"
  name: Build $(date +'%d.%m.%Y %R')
  skip-cleanup: true
